export const firebaseEnv = {
    API_KEY: import.meta.env.VITE_GESTOR_FIREBASE_API_KEY,
    APP_ID: import.meta.env.VITE_APP_GESTOR_FIREBASE_APP_ID,
    AUTH_DOMAIN: import.meta.env.VITE_APP_GESTOR_FIREBASE_AUTH_DOMAIN,
    MEASUREMENT_ID: import.meta.env.VITE_APP_GESTOR_FIREBASE_MEASUREMENT_ID,
    MESSAGING_SENDER_ID: import.meta.env.VITE_APP_GESTOR_FIREBASE_MESSAGING_SENDER_ID,
    PROJECT_ID: import.meta.env.VITE_APP_GESTOR_FIREBASE_PROJECT_ID,
    STORAGE_BUCKET: import.meta.env.VITE_APP_GESTOR_FIREBASE_STORAGE_BUCKET
} as const;